apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: pullrequest
spec:
  pipelineSpec:
    tasks:
    - name: test
      taskSpec:
        steps:
        - image: uses:lighthouse:devops/jx3-pipeline-catalog-keyfactor/tasks/java-jar/pullrequest.yaml@HEAD
  serviceAccountName: tekton-bot
  timeout: 10m
