name: Create a release
on:
  push:
    tags:
    - "v[0-9]+.[0-9]+.[0-9]+"
jobs:
    release:
        name: Release
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: Run tests
          uses: docker/build-push-action@v5
          with:
            context: .
            platforms: linux/amd64
            push: false
        - name: Setup Java
          uses: actions/setup-java@v4
          with:
            java-version: '11'
            distribution: 'temurin'
        - name: Build
          run: |
            mvn --no-transfer-progress -DskipTests package
        - name: Release
          uses: softprops/action-gh-release@master
          with:
            files: target/*.jar
        - name: Publish package
          run: mvn --no-transfer-progress -DskipTests deploy
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}